/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FTPGUI.java
 *
 * Created on 2011-11-29, 3:37:04
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * 
 * @author Administrator
 */
public class FTPGUI extends javax.swing.JFrame {

	static final String USER_HOME = System.getProperty("user.home");
	private FTPClient client;
	private File currentpath;
	private File[] localfiles;
	private FileElement[] remotefiles;

	/** Creates new form FTPGUI */
	public FTPGUI() {
		currentpath = new File(USER_HOME);
		remotefiles = new FileElement[0];
		createLocalFileList();
		initComponents();
		localTextField.setText(currentpath.getAbsolutePath());
	}

	public void writeOutput(String text) {
		testoutput.append(text.trim());
		testoutput.append("\n");
	}

	private void createLocalFileList() {
		File[] files = currentpath.listFiles();
		LinkedList<File> filecollection = new LinkedList<File>();
		for (File f : files) {
			// testoutput.append(f.getName());
			if (f.isDirectory()) {
				filecollection.add(0, f);
			} else {
				filecollection.add(f);
			}
		}
		filecollection.add(0, new File(".."));
		localfiles = new File[filecollection.size()];
		filecollection.toArray(localfiles);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		localPopupMenu = new javax.swing.JPopupMenu();
		remotePopupMenu = new javax.swing.JPopupMenu();
		headPanel = new javax.swing.JPanel();
		connectPanel = new javax.swing.JPanel();
		hostLabel = new javax.swing.JLabel();
		hostTextField = new javax.swing.JTextField();
		usernameLabel = new javax.swing.JLabel();
		usernameTextField = new javax.swing.JTextField();
		passwordLabel = new javax.swing.JLabel();
		portLabel = new javax.swing.JLabel();
		portTextField = new javax.swing.JTextField();
		connectButton = new javax.swing.JButton();
		PasswordField = new javax.swing.JPasswordField();
		disconnectButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		testoutput = new javax.swing.JTextArea();
		localPanel = new javax.swing.JPanel();
		localSeparator = new javax.swing.JSeparator();
		localLabel = new javax.swing.JLabel();
		localTextField = new javax.swing.JTextField();
		localScrollPane = new javax.swing.JScrollPane();
		localList = new javax.swing.JList();
		remotePanel = new javax.swing.JPanel();
		remoteSeparator = new javax.swing.JSeparator();
		remoteLabel = new javax.swing.JLabel();
		remoteTextField = new javax.swing.JTextField();
		remoteScrollPane = new javax.swing.JScrollPane();
		remoteList = new javax.swing.JList();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		smMenuItem = new javax.swing.JMenuItem();
		exportMenuItem = new javax.swing.JMenuItem();
		importMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		pasvMenuItem = new javax.swing.JCheckBoxMenuItem();
		securedMenuItem = new javax.swing.JCheckBoxMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		hostLabel.setText("Host:");

		hostTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hostTextFieldActionPerformed(evt);
			}
		});

		usernameLabel.setText("Username:");

		usernameTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				usernameTextFieldActionPerformed(evt);
			}
		});

		passwordLabel.setText("Password:");

		portLabel.setText("Port:");

		portTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				portTextFieldKeyTyped(evt);
			}
		});

		connectButton.setText("Connect");
		connectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				connectButtonActionPerformed(evt);
			}
		});

		PasswordField.setText("");

		disconnectButton.setText("Disconnect");
		disconnectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				disconnectButtonActionPerformed(evt);
			}
		});

		testoutput.setColumns(20);
		testoutput.setRows(5);
		jScrollPane1.setViewportView(testoutput);

		javax.swing.GroupLayout connectPanelLayout = new javax.swing.GroupLayout(connectPanel);
		connectPanel.setLayout(connectPanelLayout);
		connectPanelLayout
				.setHorizontalGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						connectPanelLayout.createSequentialGroup().addGroup(
								connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(
										jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE).addGroup(
										connectPanelLayout.createSequentialGroup().addContainerGap().addComponent(hostLabel)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
														hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
														javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(usernameLabel)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
														usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
														javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(passwordLabel)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
														PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
														javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(portLabel)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
														portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
														javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
												.addComponent(connectButton).addGap(18, 18, 18).addComponent(disconnectButton)))
								.addContainerGap()));
		connectPanelLayout.setVerticalGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				connectPanelLayout.createSequentialGroup().addGroup(
						connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(hostTextField,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(hostLabel).addComponent(usernameLabel).addComponent(
								usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(passwordLabel).addComponent(PasswordField,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(portLabel)
								.addComponent(disconnectButton).addComponent(connectButton)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE).addContainerGap()));

		javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
		headPanel.setLayout(headPanelLayout);
		headPanelLayout.setHorizontalGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				headPanelLayout.createSequentialGroup().addContainerGap().addComponent(connectPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		headPanelLayout.setVerticalGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				headPanelLayout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(connectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		localLabel.setText("Local Site:");

		localList.setModel(new javax.swing.AbstractListModel() {
			public int getSize() {
				return localfiles.length;
			}

			public Object getElementAt(int i) {

				return localfiles[i].getName() + (localfiles[i].isDirectory() && !localfiles[i].getName().equals("..") ? "/" : "");
			}
		});
		localList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				localListMouseReleased(evt);
			}

			public void mouseClicked(java.awt.event.MouseEvent evt) {
				localListMouseClicked(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				localListMousePressed(evt);
			}
		});
		localList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				localListMouseDragged(evt);
			}
		});
		localScrollPane.setViewportView(localList);
		localList.add(localPopupMenu);

		JMenuItem menu = new JMenuItem("Upload");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu); // 娣诲����椤�pen

		menu = new JMenuItem("Enter directory");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu);

		menu = new JMenuItem("Create directory");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu);

		menu = new JMenuItem("Refresh");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu);

		menu = new JMenuItem("Delete");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu);

		menu = new JMenuItem("Rename");
		menu.addActionListener(localMenuListener);
		localPopupMenu.add(menu);

		localList.setDragEnabled(true);
		localList.setTransferHandler(new FileListTransferHandler(this, 0));

		javax.swing.GroupLayout localPanelLayout = new javax.swing.GroupLayout(localPanel);
		localPanel.setLayout(localPanelLayout);
		localPanelLayout.setHorizontalGroup(localPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				localSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE).addGroup(
				localPanelLayout.createSequentialGroup().addContainerGap().addComponent(localLabel).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(localTextField,
						javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE).addContainerGap()).addComponent(localScrollPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE));
		localPanelLayout.setVerticalGroup(localPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				localPanelLayout.createSequentialGroup().addComponent(localSeparator, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						localPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(localLabel)
								.addComponent(localTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(localScrollPane,
						javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE).addContainerGap()));

		remoteLabel.setText("Remote Site:");

		remoteList.setModel(new javax.swing.AbstractListModel() {

			public int getSize() {
				return remotefiles.length;
			}

			public Object getElementAt(int i) {
				return remotefiles[i].toString();
			}
		});
		remoteList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				remoteListMouseReleased(evt);
			}

			public void mouseClicked(java.awt.event.MouseEvent evt) {
				remoteListMouseClicked(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				remoteListMousePressed(evt);
			}
		});
		remoteList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				remoteListMouseDragged(evt);
			}
		});
		remoteScrollPane.setViewportView(remoteList);
		remoteList.add(localPopupMenu);

		menu = new JMenuItem("Download");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu); // 娣诲����椤�pen

		menu = new JMenuItem("Enter directory");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu);

		menu = new JMenuItem("Create directory");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu);

		menu = new JMenuItem("Refresh");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu);

		menu = new JMenuItem("Delete");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu);

		menu = new JMenuItem("Rename");
		menu.addActionListener(remoteMenuListener);
		remotePopupMenu.add(menu);

		remoteList.setDragEnabled(true);
		remoteList.setTransferHandler(new FileListTransferHandler(this, 1));

		javax.swing.GroupLayout remotePanelLayout = new javax.swing.GroupLayout(remotePanel);
		remotePanel.setLayout(remotePanelLayout);
		remotePanelLayout.setHorizontalGroup(remotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				remoteSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE).addGroup(
				remotePanelLayout.createSequentialGroup().addContainerGap().addComponent(remoteLabel).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(remoteTextField,
						javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE).addContainerGap()).addGroup(
				remotePanelLayout.createSequentialGroup().addComponent(remoteScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441,
						Short.MAX_VALUE).addContainerGap()));
		remotePanelLayout.setVerticalGroup(remotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				remotePanelLayout.createSequentialGroup().addComponent(remoteSeparator, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						remotePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(remoteLabel)
								.addComponent(remoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(remoteScrollPane,
						javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		fileMenu.setMnemonic('f');
		fileMenu.setText("File");

		smMenuItem.setMnemonic('m');
		smMenuItem.setText("Site Manager");
		fileMenu.add(smMenuItem);

		exportMenuItem.setMnemonic('e');
		exportMenuItem.setText("Export");
		fileMenu.add(exportMenuItem);

		importMenuItem.setMnemonic('i');
		importMenuItem.setText("Import");
		fileMenu.add(importMenuItem);

		exitMenuItem.setMnemonic('x');
		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		editMenu.setMnemonic('e');
		editMenu.setText("Edit");

		pasvMenuItem.setSelected(true);
		pasvMenuItem.setText("Passive mode");
		editMenu.add(pasvMenuItem);

		securedMenuItem.setText("Secure mode");
		editMenu.add(securedMenuItem);

		menuBar.add(editMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(localPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(31, 31, 31).addComponent(
						remotePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(headPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(remotePanel,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(localPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuItemActionPerformed

	private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_connectButtonActionPerformed
		// TODO add your handling code here:
		String host = hostTextField.getText();
		String username = usernameTextField.getText();
		char[] password = PasswordField.getPassword();
		String port = portTextField.getText();
		int p;
		try {
			p = Integer.parseInt(port);
		} catch (Exception e) {
			p = 21;
		}
		client = new FTPClient(host, p, username, new String(password));
		client.setPassiveMode(pasvMenuItem.isSelected());
		client.setSecureMode(securedMenuItem.isSelected());
		try {
			if (client.openConnection()) {
				client.printWorkingDir();
				this.writeOutput(client.getOutputs());
				remoteTextField.setText(client.getRemoteWorkingDir());
				refreshRemote();
			} else {
				this.writeOutput("Can't open connection to server, check your input.");
			}
		} catch (Exception e) {
			if (e instanceof java.net.UnknownHostException) {
				this.writeOutput("Host unknown: " + e.getMessage());
				client = null;
			}
		}
	}// GEN-LAST:event_connectButtonActionPerformed

	private void localListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_localListMouseClicked
		// TODO add your handling code here:
		if (evt.getClickCount() == 2) { // When double click JList
			enterDir();
		}
	}// GEN-LAST:event_localListMouseClicked

	private ActionListener localMenuListener = new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
			String menu = e.getActionCommand();
			if (menu.equals("Upload")) {
				upload();
			} else if (menu.equals("Enter directory")) {
				enterDir();
			} else if (menu.equals("Create directory")) {
				createDir();
			} else if (menu.equals("Refresh")) {
				refresh();
			} else if (menu.equals("Delete")) {
				delete();
			} else if (menu.equals("Rename")) {
				rename();
			}
		}
	};
	private ActionListener remoteMenuListener = new ActionListener() {

		@Override
		public void actionPerformed(ActionEvent e) {
			String menu = e.getActionCommand();
			if (menu.equals("Download")) {
				download();
			} else if (menu.equals("Enter directory")) {
				enterRemoteDir();
			} else if (menu.equals("Create directory")) {
				createRemoteDir();
			} else if (menu.equals("Refresh")) {
				refreshRemote();
			} else if (menu.equals("Delete")) {
				deleteRemote();
			} else if (menu.equals("Rename")) {
				renameRemote();
			}
		}
	};

	public void upload() {
		int select = localList.getSelectedIndex();
		if (select < 0 || select >= localfiles.length) {
			return;
		}
		if (client != null && localfiles[select].isFile()) {
			try {
				if (client.store(localfiles[select].getCanonicalPath())) {
					// The file is uploaded successfully
					refreshRemote();
					this.writeOutput(client.getOutputs());
				}
			} catch (IOException ex) {
				Logger.getLogger(FTPGUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		}

	}

	private void enterDir() {
		int select = localList.getSelectedIndex();
		if (select < 0 || select >= localfiles.length) {
			return;
		}
		File selectFile = localfiles[select];
		if (selectFile.isDirectory()) {
			if (selectFile.getName().equals("..")) {
				currentpath = currentpath.getParentFile();
			} else {
				currentpath = selectFile;
			}
			localTextField.setText(currentpath.getAbsolutePath());
			refresh();
		}

	}

	private void createDir() {
		int select = localList.getSelectedIndex();
		if (select < 0 || select >= localfiles.length) {
			return;
		}
		showDialog("New folder", new KeyListener() {

			@Override
			public void keyPressed(KeyEvent evt) {
				if (evt.getKeyCode() == 27) {
					dialog.setVisible(false);
				}
			}

			@Override
			public void keyReleased(KeyEvent evt) {
			}

			@Override
			public void keyTyped(KeyEvent evt) {
				if (evt.getKeyChar() == '\n') {
					String foldername = tf.getText();
					File newfolder = new File(currentpath.getAbsolutePath() + "/" + foldername);
					if (!newfolder.exists()) {
						newfolder.mkdir();
						refresh();
					}
					dialog.setVisible(false);
				}
			}

		});
	}

	private void showDialog(String eventname, KeyListener listener) {
		tf = new JTextField(eventname, 20);
		dialog = new JDialog();
		JPanel panel = new JPanel();
		panel.add(tf);
		dialog.setLocation(100, 250);
		dialog.setSize(230, 50);
		dialog.setContentPane(panel);
		tf.addKeyListener(listener);
		dialog.setVisible(true);
	}

	private JTextField tf;
	JDialog dialog;

	private void refresh() {
		createLocalFileList();
		localList.setSelectedIndex(0);
		localList.scrollRectToVisible(localList.getCellBounds(0, 0));
		localList.invalidate();
		localList.repaint();
	}

	private void delete() {
		int select = localList.getSelectedIndex();
		if (select < 0 || select >= localfiles.length) {
			return;
		}
		localfiles[select].delete();
		refresh();
	}

	private void rename() {
		final int select = localList.getSelectedIndex();
		if (select < 0 || select >= localfiles.length) {
			return;
		}
		showDialog(localfiles[select].getName(), new KeyListener() {

			@Override
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == 27) {
					dialog.setVisible(false);
				}
			}

			@Override
			public void keyTyped(KeyEvent e) {
				if (e.getKeyChar() == '\n') {
					String foldername = tf.getText();
					File oldfile = localfiles[select];
					if (!oldfile.getName().equals(foldername)) {
						File newfile = new File(oldfile.getParent() + "/" + foldername);
						oldfile.renameTo(newfile);
						refresh();
					}
					dialog.setVisible(false);
				}
			}

			@Override
			public void keyReleased(KeyEvent e) {
			}

		});
	}

	public void download() {
		int select = remoteList.getSelectedIndex();
		if (select < 0 || select >= remotefiles.length) {
			return;
		}
		// testoutput.append(currentpath.getAbsolutePath());
		try {
			boolean result = client.retrieve(remotefiles[select].getFileName(), currentpath.getAbsolutePath());
			if (result) {
				this.writeOutput(client.getOutputs());
				refresh();
			}
		} catch (Exception ex) {
			Logger.getLogger(FTPGUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void enterRemoteDir() {
		int select = remoteList.getSelectedIndex();
		if (select != -1 && client != null) {
			try {
				client.changeDir(remotefiles[select].getFileName());
				remoteTextField.setText(client.getRemoteWorkingDir());
				this.writeOutput(client.getOutputs());
				refreshRemote();
			} catch (IOException ex) {
				Logger.getLogger(FTPGUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}

	private void createRemoteDir() {
		showDialog("New Folder", new KeyListener() {

			@Override
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == 27)
					dialog.setVisible(false);
			}

			@Override
			public void keyReleased(KeyEvent e) {
			}

			@Override
			public void keyTyped(KeyEvent e) {
				if (e.getKeyChar() == '\n') {
					String foldername = tf.getText();
					try {
						if (client != null && client.makeDirectory(foldername))
							refreshRemote();
					} catch (IOException e1) {
						e1.printStackTrace();
					}

					dialog.setVisible(false);
				}
			}

		});
	}

	private void deleteRemote() {
		int select = remoteList.getSelectedIndex();
		if (select < 0 || select > remotefiles.length || client == null) {
			return;
		}
		try {
			if (client.delete(remotefiles[select].getFileName())) {
				this.writeOutput(client.getOutputs());
				refreshRemote();
			}
		} catch (IOException ex) {
			Logger.getLogger(FTPGUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void renameRemote() {
		final int select = remoteList.getSelectedIndex();
		if (select < 0 || select > remotefiles.length || client == null) {
			return;
		}
		showDialog(remotefiles[select].getFileName(), new KeyListener() {

			@Override
			public void keyPressed(KeyEvent e) {
				if (e.getKeyCode() == 27)
					dialog.setVisible(false);
			}

			@Override
			public void keyReleased(KeyEvent e) {
			}

			@Override
			public void keyTyped(KeyEvent e) {
				if (e.getKeyChar() == '\n') {
					String oldname = remotefiles[select].getFileName();
					String foldername = tf.getText();
					try {
						if (client != null && !oldname.equals(foldername) && client.rename(oldname, foldername))
							refreshRemote();
					} catch (IOException e1) {
						e1.printStackTrace();
					}

					dialog.setVisible(false);
				}
			}

		});
	}

	private void refreshRemote() {
		try {
			remotefiles = client.list();
			remoteList.setListData(remotefiles);
			remoteList.invalidate();
			remoteList.repaint();
			this.writeOutput(client.getOutputs());
		} catch (IOException ex) {
			Logger.getLogger(FTPGUI.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void localListMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_localListMousePressed
		// TODO add your handling code here:
		if (evt.isPopupTrigger() && localList.getSelectedIndex() != -1) {
			// �峰����椤圭��� Object selected =
			// localList.getModel().getElementAt(localList.getSelectedIndex());
			// testoutput.append(selected.toString());
			localPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}// GEN-LAST:event_localListMousePressed

	private void localListMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_localListMouseReleased
		// TODO add your handling code here:
		if (evt.isPopupTrigger() && localList.getSelectedIndex() != -1) {
			// �峰����椤圭��� Object selected =
			// localList.getModel().getElementAt(localList.getSelectedIndex());
			// testoutput.append(selected.toString());
			localPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}// GEN-LAST:event_localListMouseReleased

	private void remoteListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_remoteListMouseClicked
		// TODO add your handling code here:
		if (evt.getClickCount() == 2) { // When double click JList
			enterRemoteDir();
		}
	}// GEN-LAST:event_remoteListMouseClicked

	private void remoteListMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_remoteListMousePressed
		// TODO add your handling code here:
		if (evt.isPopupTrigger() && remoteList.getSelectedIndex() != -1) {
			// �峰����椤圭��� Object selected =
			// remoteList.getModel().getElementAt(remoteList.getSelectedIndex());
			remotePopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}// GEN-LAST:event_remoteListMousePressed

	private void remoteListMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_remoteListMouseReleased
		// TODO add your handling code here:
		if (evt.isPopupTrigger() && remoteList.getSelectedIndex() != -1) {
			// �峰����椤圭��� Object selected =
			// remoteList.getModel().getElementAt(remoteList.getSelectedIndex());
			remotePopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
		}
	}// GEN-LAST:event_remoteListMouseReleased

	private void localListMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_localListMouseDragged
		// TODO add your handling code here:
	}// GEN-LAST:event_localListMouseDragged

	private void remoteListMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_remoteListMouseDragged
		// TODO add your handling code here:
		if ((evt.getModifiers() & MouseEvent.MOUSE_RELEASED) == MouseEvent.MOUSE_RELEASED) {
			System.out.println("Drag");
		}
	}// GEN-LAST:event_remoteListMouseDragged

	private void hostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hostTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_hostTextFieldActionPerformed

	private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_usernameTextFieldActionPerformed

	private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_disconnectButtonActionPerformed
		// TODO add your handling code here:
		try {
			client.quit();
			this.writeOutput(client.getOutputs());
			client = null;
			remotefiles = null;
			remoteList.setListData(new Object[0]);
			remoteTextField.setText("");
		} catch (Exception e) {
		}
	}// GEN-LAST:event_disconnectButtonActionPerformed

	private void portTextFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_portTextFieldKeyTyped
		// TODO add your handling code here:
		Object o = evt.getSource();
		if (o instanceof JTextField) {
			char keyCh = evt.getKeyChar();
			if ((keyCh < '0') || (keyCh > '9')) {
				if (keyCh != '\n') // ��溅瀛��
				{
					evt.setKeyChar('\0');
				}
			}
		}

	}// GEN-LAST:event_portTextFieldKeyTyped

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FTPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FTPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FTPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FTPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new FTPGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPasswordField PasswordField;
	private javax.swing.JButton connectButton;
	private javax.swing.JPanel connectPanel;
	private javax.swing.JButton disconnectButton;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenuItem exportMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JPanel headPanel;
	private javax.swing.JLabel hostLabel;
	private javax.swing.JTextField hostTextField;
	private javax.swing.JMenuItem importMenuItem;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel localLabel;
	private javax.swing.JList localList;
	private javax.swing.JPanel localPanel;
	private javax.swing.JPopupMenu localPopupMenu;
	private javax.swing.JScrollPane localScrollPane;
	private javax.swing.JSeparator localSeparator;
	private javax.swing.JTextField localTextField;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JCheckBoxMenuItem pasvMenuItem;
	private javax.swing.JLabel portLabel;
	private javax.swing.JTextField portTextField;
	private javax.swing.JLabel remoteLabel;
	private javax.swing.JList remoteList;
	private javax.swing.JPanel remotePanel;
	private javax.swing.JPopupMenu remotePopupMenu;
	private javax.swing.JScrollPane remoteScrollPane;
	private javax.swing.JSeparator remoteSeparator;
	private javax.swing.JTextField remoteTextField;
	private javax.swing.JCheckBoxMenuItem securedMenuItem;
	private javax.swing.JMenuItem smMenuItem;
	private javax.swing.JTextArea testoutput;
	private javax.swing.JLabel usernameLabel;
	private javax.swing.JTextField usernameTextField;
	// End of variables declaration//GEN-END:variables
}
